### ISSUE TITLE
Allow to add value fields to enumeration values

### ISSUE THREAD

**Issue by pedrorijo91** [rbricks/itemized#11]
I think the problem has to do with extending a `trait`. If the enums extends abstract classes it should be easy to add this behaviour. On the other hand, it would forbid to create user hierarchies on the enumeration (not sure if interesting tough). Maybe another annotation could solve this problem, by letting the user choose between the available options?

example:

```scala
sealed abstract class Weekday( val name: String,
                               val abbreviation: String,
                               val isWorkDay: Boolean)

case object Monday extends Weekday("Monday", "Mo.", true)
case object Tuesday extends Weekday("Tuesday", "Tu.", true)
case object Wednesday extends Weekday("Wednesday", "We.", true)
case object Thursday extends Weekday("Thursday", "Th.", true)
case object Friday extends Weekday("Friday", "Fr.", true)
case object Saturday extends Weekday("Saturday", "Sa.", false)
case object Sunday extends Weekday("Sunday", "Su.", false)
```

**Comment by utaal** [comment]
I'm not entirely sure of what you're looking for, here. Would you like to have the (`String` <-> `Weekday`, i.e. "Monday" <-> Monday) mappings where `Weekday` also has additional value fields? Depending on what you're looking for, this feels like it might be out of scope of the library, and probably better served by a custom implementation, but I do feel like having value fields (ignored by the mapping) may be worthwhile.
