### ISSUE TITLE
Allow to list all enumeration indices and values

### ISSUE THREAD

**Issue by pedrorijo91** [rbricks/itemized#4]
Similar to `scala.Enumeration#values` it could be interesting to find a way to return all possible values from an ItemizedEnum

---
Still wip:
* [ ] consider similar functionality for `ItemizedCodec`
* [ ] write docs

**Comment by utaal** [comment]
Hey, thank you for the PR! I've seen this done by other libraries, but I'm not yet sure what are the use cases, and I'm really committed to keeping this as small as possible. Can you share your use case for this?

**Comment by esarbe** [comment]
Hey @utaal, I've got a use case. I'm generating random instances of enumeration objects. To do that I need a set of all the possible values for a given enum type, so that I can select one of them.

**Comment by utaal** [comment]
Makes sense. Are you using scalacheck?

**Comment by esarbe** [comment]
No, actually. I'm playing with generative algorithms and need a way to explore the state-space.

**Comment by pedrorijo91** [comment]
I personally don't have any use case (yet), but it was a disadvantage I noticed when comparing to using the `scala.Enumeration`. If you (and others) think it doesn't make sense to add it feel free to close the issue. But I think it may be useful for someone, specially to ease migrations between `scala.Enumeration` and `Itemized` in a first phase.

**Comment by utaal** [comment]
Thank you both for taking the time to answer. I agree it's worthwhile, but I'd like to see whether it warrants a small refactor (so we can also support scalacheck and similar libraries): in particular, it probably does not belong in `ItemizedCodec` but should be in a separate typeclass. @esarbe if you don't mind, I'd like to try and work on top of your PR branch.

**Comment by esarbe** [comment]
@utaal Sure, go ahead! If I can be of any help, just let me know. :D

**Comment by utaal** [comment]
Ok, I've merged @esarbe's PR with my modifications.
You can use `ItemizedIndex.indexMap` to get a `Map[T#Index, T]` map of (index -> value)s.

Snapshot published:
```
"io.rbricks" %% "itemized" % "0.2-SNAPSHOT"
```

Let's try it out, once we're satisfied, I'll release `0.2.0` (possibly with something similar for `IndexedCodec`).

I'll keep this open in the meantime.

Side-note: the fact that you can allow maintainers to push on PR branches is very neat.

cc/ @esarbe, @pedrorijo91

**Comment by pedrorijo91** [comment]
getting an `sbt.ResolveException: unresolved dependency: io.rbricks#itemized_2.11;0.2-SNAPSHOT: not found`

it doesn't seem to be published on maven central either: http://search.maven.org/#search%7Cga%7C1%7Citemized

(solved by publishing locally: `sbt +publishLocal`)

**Comment by pedrorijo91** [comment]
i've only now noticed that the new method only works for `indexedEnum`s.  Why don't simple `enums` support a similar method ?

**Comment by utaal** [comment]
@pedrorijo91 the snapshots are published in the sonatype snapshot repo; add

```
resolvers += Resolver.sonatypeRepo("snapshots")
```

to build.sbt.

**Comment by utaal** [comment]
Regarding support for `IndexedEnum`, I'm taking a look on how to do it cleanly: suggestions welcome!

**Comment by utaal** [comment]
@pedrorijo91 here's the current plan https://github.com/rbricks/itemized/pull/9
You can get to all values with `stringMap.values` and to all string encodings with `stringMap.keys`.
Would something like this work for you?

**Comment by pedrorijo91** [comment]
yes,  it seems to do the work :)
